export const ROUTES_NAME = {
  WELCOME: "welcome",
  REGISTER_MANUAL: "register_manual",
  REGISTER_IMPOR: "register_impor",
  CREATE_PROFILE_ADMIN: "create_profile_admin",
  CREATE_PIN_ADMIN: "create_admin_pin",
  ABOUT_ARISAN: "ABOUT_ARISAN",
  DUES: "dues",
  MEMBER_COUNT: "member_count",
  PAYMENT_TERM: "payment_term",
  WINNERS: "winners",
  GIFT: "GIFT",
  ENTRY_MEMBER: "entry_member",
  HOME: "home",
};
