export enum TypesReducer {
  SET_ADMINISTRATOR_DATA = "SET_ADMINISTRATOR_DATA",
  CHANGE_LANGUAGE = "CHANGE_LANGUAGE",
  CHANGE_CURRENT_ROUTES = "CHANGE_CURRENT_ROUTES",
  CHANGE_PREVIOUS_ROUTES = "CHANGE_PREVIOUS_ROUTES",
  CHANGE_NEXT_ROUTES = "CHANGE_NEXT_ROUTES",
}
